schema-version = "1.11.0"

[install]
nodejs.pkg-path = "nodejs_24"
nodejs.version = "24.15.0"
claude-code.pkg-path = "claude-code"
claude-code.version = "^2.1.148"
infer.flake = "github:inference-gateway/cli/v0.112.0"

[hook]
on-activate = """
  npm install
"""
