schema-version = "1.11.0"

[install]
nodejs.pkg-path = "nodejs_24"
nodejs.version = "24.14.0"
claude-code.pkg-path = "claude-code"
claude-code.version = "2.1.112"

[hook]
on-activate = """
  npm install
"""
